### ISSUE TITLE
Hardware an Gleis anschließen für DCC Signal?

### ISSUE THREAD

**Issue by xbromy** [littleyoda/littleyoda-DCC-Decoder#1]
Hallo,

ich lese mich gerade in diese Projekt ein wenig ein. Ich suche für Märklin H0 mit einer MS2 eine günstige Alternative Servos und auch Relais zu schalten und möchte das gern mit einem NodeMCU und diesem Projekt versuchen. Was ich nicht finde ist: Wie drahte ich den NodeMCU an? Also woher bekommt er wie das DCC Signal?
An welche GIPOs und wie dann weiter..
Vielen Dank! 
Gruß Dirk

**Comment by littleyoda** [comment]
Den Schaltplan für den DCC anbei ...
[weiche.pdf](https://github.com/littleyoda/littleyoda-DCC-Decoder/files/2202757/weiche.pdf)

Meld dich einfach mal per E-Mail bei mir, dann kann ich dir ggf. einfacher helfen.
